name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto si usas una rama diferente para el despliegue

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Cambia esto según la versión de Node.js que uses

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --output-path=docs --base-href=/nombre-del-repositorio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
